SCREEN_W, SCREEN_H = 800, 600
SCREEN_SIZE = (SCREEN_W, SCREEN_H)
GROUND_HEIGHT = SCREEN_H - 62

BG_MULTI = 2.68
PLAYER_MULTI = 2.9

GRAVITY = 1.0
ANTI_GRAVITY = 0.3

VOLUMN_THRESHOLD = 3500

FONT = 'FixedSys.ttf'